<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\character_community.png" />
    <None Remove="Assets\character_community_beta.png" />
    <None Remove="Assets\character_community_decapo.png" />
    <None Remove="Assets\character_community_festa.png" />
    <None Remove="Assets\character_community_hermies.png" />
    <None Remove="Assets\character_community_opal.png" />
    <None Remove="Assets\character_community_tempo.png" />
    <None Remove="Assets\character_community_vam.png" />
    <None Remove="Assets\character_community_zeta.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\character_community.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\character_community_beta.png" />
    <EmbeddedResource Include="Assets\character_community_decapo.png" />
    <EmbeddedResource Include="Assets\character_community_festa.png" />
    <EmbeddedResource Include="Assets\character_community_hermies.png" />
    <EmbeddedResource Include="Assets\character_community_opal.png" />
    <EmbeddedResource Include="Assets\character_community_tempo.png" />
    <EmbeddedResource Include="Assets\character_community_vam.png" />
    <EmbeddedResource Include="Assets\character_community_zeta.png" />
    <None Remove="Assets\character_community_zeta_black.png" />
    <EmbeddedResource Include="Assets\character_community_zeta_black.png" />
    <None Remove="Assets\character_community_zeta_city.png" />
    <EmbeddedResource Include="Assets\character_community_zeta_city.png" />
    <None Remove="Assets\character_community_zeta_directer.png" />
    <EmbeddedResource Include="Assets\character_community_zeta_directer.png" />
    <None Remove="Assets\character_community_zeta_moon.png" />
    <EmbeddedResource Include="Assets\character_community_zeta_moon.png" />
    <None Remove="Assets\character_community_zeta_seawinds.png" />
    <EmbeddedResource Include="Assets\character_community_zeta_seawinds.png" />
    <None Remove="Assets\character_community_zeta_stone.png" />
    <EmbeddedResource Include="Assets\character_community_zeta_stone.png" />
    <None Remove="Assets\character_community_zeta_sun.png" />
    <EmbeddedResource Include="Assets\character_community_zeta_sun.png" />
    <None Remove="Assets\character_community_zeta_volcano.png" />
    <EmbeddedResource Include="Assets\character_community_zeta_volcano.png" />
    <None Remove="Assets\character_community_zeta_new.png" />
    <None Remove="Assets\character_community_innerRing.png" />
    <EmbeddedResource Include="Assets\character_community_innerRing.png" />
    <None Remove="Assets\character_community_outerRing.png" />
    <EmbeddedResource Include="Assets\character_community_outerRing.png" />
    <None Remove="Assets\textures" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(Net6)\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="CoffinTech">
      <HintPath>$(VSDir)\Mods\CoffinTech.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppDOTween">
      <HintPath>$(Il2)\Il2CppDOTween.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>$(Net6)\Il2CppInterop.Runtime.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2CppMAScripts">
      <HintPath>$(Il2)\Il2CppMAScripts.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>$(Il2)\Il2Cppmscorlib.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2CppNewtonsoft.Json">
      <HintPath>$(Il2)\Il2CppNewtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2CppPauseSystem">
      <HintPath>$(Il2)\Il2CppPauseSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2CppPhaserPort">
      <HintPath>$(Il2)\Il2CppPhaserPort.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2CppProCamera2D">
      <HintPath>$(Il2)\Il2CppProCamera2D.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppRewired_Core">
      <HintPath>$(Il2)\Il2CppRewired_Core.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSirenix.Serialization">
      <HintPath>$(Il2)\Il2CppSirenix.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSystem">
      <HintPath>$(Il2)\Il2CppSystem.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSystem.Core">
      <HintPath>$(Il2)\Il2CppSystem.Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2CppVampireSurvivors.Runtime">
      <HintPath>$(Il2)\Il2CppVampireSurvivors.Runtime.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2CppZenject">
      <HintPath>$(Il2)\Il2CppZenject.dll</HintPath>
    </Reference>
    <Reference Include="MelonLoader">
      <HintPath>$(Net6)\MelonLoader.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(Net6)\Newtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.Burst">
      <HintPath>$(Il2)\Unity.Burst.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Burst.Unsafe">
      <HintPath>$(Il2)\Unity.Burst.Unsafe.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Collections">
      <HintPath>$(Il2)\Unity.Collections.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>$(Il2)\Unity.Mathematics.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(Il2)\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(Il2)\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(Il2)\UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(Il2)\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>$(Il2)\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(Il2)\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(Il2)\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(Il2)\UnityEngine.UIModule.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="TestController.cs" />
    <Compile Remove="InbetweenController.cs" />
    <Compile Remove="JsonConverter.cs" />
  </ItemGroup>
</Project>
